# -*- coding: utf-8 -*-
"""BasicDS6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sCn8znnebjemWHVt1QNSVuoQYOiGhmd
"""

import matplotlib.pyplot as plt
import numpy as np

# prompt: icecream_sales.csvを読み込んで

import pandas as pd

# icecream_sales.csvを読み込む
df = pd.read_csv('icecream_sales.csv')

# データフレームを表示
print(df)

df.head()

# prompt: DataFrame df を使用: 「男性と女性で味に好みの違いがあるか」という仮説を検証して

# ライブラリのインポート
import pandas as pd
from scipy import stats

# 「男性」と「女性」でグループ化し、味の好みを比較
male_preferences = df[df['性別'] == '男性']['味'].value_counts()
female_preferences = df[df['性別'] == '女性']['味'].value_counts()

# chi2検定で独立性の検定を行う
contingency_table = pd.crosstab(df['性別'], df['味'])
chi2, p, _, _ = stats.chi2_contingency(contingency_table)

# 結果を表示
print("カイ二乗統計量:", chi2)
print("p値:", p)

# p値が0.05より小さい場合、帰無仮説（男性と女性の味の好みは独立である）を棄却
if p < 0.05:
    print("男性と女性で味の好みには有意な差があると考えられます。")
else:
    print("男性と女性で味の好みには有意な差があるとは言えません。")

# 男性と女性の味の好みを比較する棒グラフを作成
# （Altairなどのライブラリを利用）

df.head()

# @title 曜日

from matplotlib import pyplot as plt
df['曜日'].plot(kind='hist', bins=20, title='曜日')
plt.gca().spines[['top', 'right',]].set_visible(False)