# -*- coding: utf-8 -*-
"""BasicDS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJO6a3n5o_nDDKT3rVxWITncb-04SZ1m

リスト1-1
"""

print("Hello")

"""リスト1-2"""

import pandas as pd
df = pd.DataFrame({"値段": [100, 120, 110, 130]})
df

"""リスト1-3"""

!pip install japanize-matplotlib
import pandas as pd
import numpy as np
import japanize_matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font=["IPAexGothic"])

"""リスト1-4"""

df.plot()
plt.title("値段の推移")
plt.show()